#!/usr/bin/env bash

COMMAND="$1"
shift

if [ "$COMMAND" == "" ]; then
    echo "Error: command is missing"
    echo "Possible commands: "
    echo "- Into php: reset, composer-install, composer-update, unit-tests"
    echo "- To enter into the php container: shell, shellroot"
    echo "- to enter into a interactive sql shell: pgsql, mysql"
    exit 1;
fi

case $COMMAND in
    reset)
        docker exec -t -i jdao_test_php appctl.sh reset
      ;;
    composer-install)
        docker exec -t -i jdao_test_php appctl.sh composer-install;;
    composer-update)
        docker exec -t -i jdao_test_php appctl.sh composer-update;;
    unit-tests)
        docker exec -t -i jdao_test_php appctl.sh unit-tests;;
    shell)
       docker exec -it --user usertest jdao_test_php  /bin/bash -l;;
    shellroot)
       docker exec -it jdao_test_php  /bin/bash  -l;;
    pgsql)
      docker exec -it --user postgres -e PGPASSWORD="jelixpass" jdao_test_pgsql psql --username=jelix jelixtests
      ;;
    mysql)
      docker exec -it jdao_test_mysql mysql -u jelix -pjelixpass jelixtests
      ;;
    *)
        echo "wrong command"
        exit 2
        ;;
esac

